export const FUNDAMENTAL_RIGHTS = [
  "Derecho a la vida",
  "Derecho a la dignidad humana",
  "Derecho a la igualdad",
  "Derecho a la salud",
  "Derecho a la educación",
  "Derecho al debido proceso",
  "Derecho al mínimo vital",
  "Derecho al libre desarrollo de la personalidad",
  "Derecho de petición",
  "Derecho al trabajo",
  "Derecho a la libertad de expresión",
  "Derecho a la intimidad",
  "Derecho a la libertad de culto",
  "Derecho a la libertad de locomoción",
  "Derecho a la seguridad social",
  "Derecho a la protección especial de grupos vulnerables (niños, personas mayores, población LGBTI, etc.)",
];
