import { SidebarProvider } from "@/components/ui/sidebar";

import type { Metadata } from "next";
import "../globals.css";
import NavbarDashboard from "@/components/Navbar/NavbarDashboard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SidebarProvider>
        <main className="flex-1 flex-col">
          <NavbarDashboard />
          <div className="flex-1 flex-col px-6 py-4">{children}</div>
        </main>
      </SidebarProvider>
    </>
  );
}
